### ISSUE TITLE
Series commitment counts are not updated on Season page

### ISSUE THREAD

**Issue by bwells78** [bwells78/ssc-react#10]
Data may not be updating. I updated my commitments to say I was doing all the concerts - but the series all list “0 tenors”.

**Comment by andymagee** [comment]
This PR addresses part of the issue: https://github.com/bwells78/ssc-react/pull/13

But for the women-only concerts this year, the total count of singers isn't correct. I don't think I fully understand the commitment data - are there entries in the backend for the men who aren't singing that concert as well?

**Comment by bwells78** [comment]
This is so cool, thank you so much!  I'm a little puzzled too, but probably just cuz my brain is fried- will figure out what's going on very soon and let you know 💯
